apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "aiven-operator.fullname" . }}-role
  namespace: {{ include "aiven-operator.namespace" . }}
  labels:
    {{- include "aiven-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - cassandras
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - cassandras/finalizers
    verbs:
      - update
  - apiGroups:
      - aiven.io
    resources:
      - cassandras/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - clickhouses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - clickhouses/finalizers
    verbs:
      - update
  - apiGroups:
      - aiven.io
    resources:
      - clickhouses/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - clickhouseusers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - clickhouseusers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - connectionpools
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - connectionpools/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - databases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - databases/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - grafanas
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - grafanas/finalizers
    verbs:
      - update
  - apiGroups:
      - aiven.io
    resources:
      - grafanas/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - kafkaacls
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - kafkaacls/status
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - kafkaconnectors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - kafkaconnectors/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - kafkaconnects
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - kafkaconnects/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - kafkas
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - kafkas/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - kafkaschemas
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - kafkaschemas/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - kafkatopics
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - kafkatopics/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - mysqls
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - mysqls/finalizers
    verbs:
      - update
  - apiGroups:
      - aiven.io
    resources:
      - mysqls/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - opensearches
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - opensearches/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - postgresqls
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - postgresqls/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - projects
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - projects/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - projectvpcs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - projectvpcs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - redis
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - redis/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - serviceintegrations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - serviceintegrations/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - aiven.io
    resources:
      - serviceusers
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - serviceusers/status
    verbs:
      - get
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
