{{- if and .Values.clusterRole.create (not .Values.watchedNamespaces) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aiven-operator.fullname" . }}-rolebinding
  namespace: {{ include "aiven-operator.namespace" . }}
  labels:
    {{- include "aiven-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aiven-operator.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "aiven-operator.serviceAccountName" . }}
  namespace: {{ include "aiven-operator.namespace" . }}
{{- end }}
