apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aiven-operator.fullname" . }}
  namespace: {{ include "aiven-operator.namespace" . }}
  labels:
{{- include "aiven-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{- include "aiven-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
{{- with .Values.podAnnotations }}
      annotations:
{{- toYaml . | nindent 8 }}
{{- end }}
      labels:
{{- include "aiven-operator.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10

{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml . | nindent 8 }}
{{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /manager
          args: 
          - --enable-leader-election
          env:

{{- if ( not .Values.webhooks.enabled ) }}
          - name: ENABLE_WEBHOOKS
            value: "false"
{{- end }}

          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP

{{- if .Values.webhooks.enabled }}
            - name: webhook
              containerPort: {{ .Values.webhooks.containerPort | default 9443 }}
              protocol: TCP
{{- end }}

          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            tcpSocket:
              port: metrics

          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            tcpSocket:
              port: metrics

          resources:
{{- toYaml .Values.resources | nindent 12 }}

{{- if .Values.webhooks.enabled }}
          volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: webhook-server-cert
            readOnly: true
{{- end }}

{{- if .Values.webhooks.enabled }}
      volumes:
      - name: webhook-server-cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
{{- end }}

{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}

{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}

{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
