{{- if .Values.clusterRole.create }}
{{- $operatorNamespace := include "aiven-operator.namespace" . }}
{{- range $watchedNamespace := prepend .Values.watchedNamespaces $operatorNamespace | uniq }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aiven-operator.fullname" $ }}-rolebinding
  namespace: {{ $watchedNamespace }}
  labels:
    {{- include "aiven-operator.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aiven-operator.fullname" $ }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "aiven-operator.serviceAccountName" $ }}
  namespace: {{ $operatorNamespace }}
{{- end }}
{{- end }}
