apiVersion: v2
name: aiven-operator
description: A Helm chart to deploy the aiven operator
type: application
version: v0.15.0
appVersion: v0.15.0
maintainers:
  - name: ivan-savciuc
    url: https://www.aiven.io
  - name: byashimov
    url: https://www.aiven.io
