replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: aiven/aiven-kubernetes-operator
  pullPolicy: IfNotPresent
  # default is .Chart.AppVersion but can be overrided here
  tag: ""

imagePullSecrets: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  webhookPort: 443

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
