apiVersion: v2
name: aiven-operator-crds
description: A Helm chart to deploy the aiven operator custom resource definitions
type: application
version: v0.12.2
appVersion: v0.12.2
maintainers:
  - name: mhoffm-aiven
    url: https://www.aiven.io
  - name: ivan-savciuc
    url: https://www.aiven.io
