apiVersion: v2
name: aiven-operator-crds
description: A Helm chart to deploy the aiven operator custom resource definitions
type: application
version: v0.14.0
appVersion: v0.14.0
maintainers:
  - name: ivan-savciuc
    url: https://www.aiven.io
  - name: murad-biashimov
    url: https://www.aiven.io
