name: Release Helm Chart
on:
  push:
    # only for the initial phase; use release tags eventually
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.2.1
